defaults:
  - setting: default
hydra:
  run:
    dir: ./synthetic #/${setting.run_file}/${setting.behavior_policy_function}/num_data=${setting.num_data_list},n_actions=${setting.n_actions}/reward_std=${setting.reward_std},beta=${setting.beta}
  sweep:
    dir: ./synthetic #/${setting.run_file}/${setting.behavior_policy_function}/num_data=${setting.num_data_list},n_actions=${setting.n_actions}/reward_std=${setting.reward_std},beta=${setting.beta}
    subdir: ./