num_runs: 50
n_unique_action: 5
len_list: 3
dim_context: 10
reward_type: "binary"
reward_structure: "standard_additive"
decay_function: "exponential"
is_factorizable: False
random_state: 12345
n_test: 5000
eps: 0.3
reward_type_conversion: "continuous"
reward_structure_conversion: "independent" #'cascade_additive', 'cascade_decay', 'independent', 'standard_additive', 'standard_decay'

#num_data
num_data_list: [125, 250, 500, 1000]